### ISSUE TITLE
Add path internal error

### ISSUE THREAD

**Issue by dracojah** [WildTurtles/remasco#1]
### What you did
J'ai essayé d'ajouter un path dans le chapitre d'histoire géographie, "Les enjeux du développement"

### What happened
En essayant d'ajouter un path, j'ai le message d'erreur suivant : Error: An Internal Error Has Occurred.
[https://ibb.co/kfJiDw](url)
### What you expected to happen
Pouvoir ajouter un path normalement

**Comment by HumanG33k** [comment]
Alors, j'ai trouvé la source du bug, en attandant que je le corrige il est contournable en éditant la matiére et en lui assignant au moins une classe.
